### ISSUE TITLE
Running into a javascript issue when trying example

### ISSUE THREAD

**Issue by cgsmith** [mrlco/yii2-google-charts#1]
I run into this issue when trying the example: 
![image](https://cloud.githubusercontent.com/assets/570018/23688044/84f724f6-0377-11e7-87e8-4a4481c4bf17.png)

**Comment by mehrna** [comment]
As you see in examples and the error message, you need to have an HTML element as "Container".

> 'containerId' => 'chart-container'

then just add this to your view file:
```html
<div id="chart-container"></div>
```
now Google Chart has a place to show up!
